import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# very simple example of a python script to plot results
# this wasn't extensively tested, it seems to work with multiple variables too

# path to dataset csv
ts = pd.read_csv("data/temperatureriver.csv")
# path to check csv generated by plugin
check = pd.read_csv("checkXXXXXXXXXX.csv")
# path to forecast csv generated by plugin
forecast = pd.read_csv("forecastXXXXXXXXXX.csv")
checkPlot = np.empty_like(ts)
checkPlot[:, :] = np.nan
checkPlot[len(ts)-len(check):len(ts)] = check
forecastPlot = np.empty((ts.shape[0] + forecast.shape[0], ts.shape[1]))
forecastPlot[:len(ts)] = np.nan
forecastPlot[len(ts):len(ts) + len(forecast)] = forecast
plt.plot(ts)
plt.plot(checkPlot)
plt.plot(forecastPlot)
plt.show()
